FROM ghcr.io/gardenlinux/gardenlinux:1592.7

RUN apt-get update && apt-get install -y lz4

RUN mkdir -p /usr/local/src/{data,conf}/ingest-debsrc/gardenlinux
RUN mkdir -p /usr/local/src/data/ingest-debsrc/gardenlinux/lists/partial

COPY conf /usr/local/src/conf

RUN apt-get update \
-o Dir="/usr/local/src/data/ingest-debsrc/gardenlinux/" \
-o Dir::Etc::sourcelist="/usr/local/src/conf/ingest-debsrc/gardenlinux.sources" \
-o Dir::State="/usr/local/src/data/ingest-debsrc/gardenlinux/"

WORKDIR /usr/local/src/data/ingest-debsrc/gardenlinux/lists/

RUN find . -name "packages.gardenlinux.io_gardenlinux_dists*source_Sources*"

ENTRYPOINT ["lz4", "-dc"]
CMD ["packages.gardenlinux.io_gardenlinux_dists_today_main_source_Sources.lz4"]
