FROM perl:bookworm

ADD https://github.com/darold/pgFormatter/archive/refs/tags/v5.6.tar.gz /pgformatter.tgz
RUN tar xf /pgformatter.tgz -C /

WORKDIR /pgFormatter-5.6

RUN perl Makefile.PL
RUN make && make install
ENTRYPOINT ["pg_format"]
