name: Code Format Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Disable for now because this fails due to github rate limit
      # - name: Run format script
      #   run: ./format-sql-schema.sh

      - name: Run Unit Tests
        run: |
          ./unit-tests.sh

      - name: Check for uncommitted changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Code is not properly formatted. Please run ./format-sql-schema.sh and commit the changes."
            exit 1
          fi
