name: Code Format Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Container for Unit Tests
        run: |
          podman build -t localhost/unit-tests:latest -f Containerfile.unit-tests .

      - name: Run Unit Tests
        run: |
          podman run -t localhost/unit-tests:latest

  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Disable for now because this fails due to github rate limit
      # - name: Run format script
      #   run: ./format-sql-schema.sh

      - name: Check for uncommitted changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "Code is not properly formatted. Please run ./format-sql-schema.sh and commit the changes."
            exit 1
          fi
