name: Data ingestion Container
on: 
  workflow_dispatch:
jobs:
  data_ingestion:
    name: data ingestion
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build image for tests
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ghcr.io/gardenlinux/glvd-data-ingestion:edge
