name: Data ingestion Container
on: 
  workflow_dispatch:
  push:
permissions:
  # Checkout repository
  contents: read
  # Push container images
  packages: write
jobs:
  data_ingestion:
    name: data ingestion
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      if: ${{ github.event_name != 'pull_request' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v6
      with:
        file: Containerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/gardenlinux/glvd-data-ingestion:edge
