name: Data ingestion Container
on: 
  workflow_dispatch:
  push:
permissions:
  # Checkout repository
  contents: read
  # Push container images
  packages: write
jobs:
  data_ingestion:
    name: data_ingestion
    runs-on: ubuntu-24.04
    env:
      IMAGE_NAME: gardenlinux/glvd-data-ingestion
      IMAGE_TAG: latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install qemu dependency for multi-arch build
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Build Image
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ env.IMAGE_TAG }}
        platforms: linux/amd64, linux/arm64
        containerfiles: |
          ./Containerfile

    - name: Push To ghcr.io
      id: push-to-ghcr
      if: ${{ github.event_name != 'pull_request' }}
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build_image.outputs.image }}
        tags: ${{ steps.build_image.outputs.tags }}
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
